### ISSUE TITLE
Stream fails to load when repost blocking is enabled

### ISSUE THREAD

**Issue by alpha-tango-kilo** [NotTobi/soundcloud-dl#12]
Hi there!

Using the latest version of the extension (1.9.1, though this also happened on 1.8.2), the [stream](https://soundcloud.com/stream) fails to load if the option "Block reposts in 'Stream' feed" is enabled. Blocking playlists works fine, but blocking reposts causes the entire stream to twiddle on a spinner for a good 15 seconds or so before then giving up - see image

![image](https://user-images.githubusercontent.com/12728900/103540445-990e2e80-4e91-11eb-9ee1-42327043d5e0.png)

Firefox 84.0.1 (though the issue has been going on for a while, I've just been too busy to file an issue), Windows 10

This was my favourite feature of the extension and I'd love to see it fixed. Let me know if you need any further information

**Comment by NotTobi** [comment]
If a song is reposted in your stream feed, it doesn't show you the track again in your feed, even if it's the original upload by the artist. In order to effectively block reposts and still show you new uploads from your followed artists, even if they have previously been reposted, the extension gathers all your followed artists on login and checks the reposts against this list. If a song of a followed artist of yours was reposted and has been released in the last 10 days, it will be converted to a regular post in your timeline. (that's why the timestamps in your feed can be off)
In your case it could be that the extension didn't register your followed artists correctly.
Try:
1. Sign out
2. Refresh the page
3. Sign in
4. Refresh the page

Let me know if this resolves your issue! :)

**Comment by alpha-tango-kilo** [comment]
Your suggested steps worked, thanks!

Could it then be possible (just an idea) to have the retry button (should it spawn) refresh the followed artists info, save having users sign out and in again?

**Comment by NotTobi** [comment]
Glad it's working again for you! :)

> Could it then be possible (just an idea) to have the retry button (should it spawn) refresh the followed artists info, save having users sign out and in again?

That's a nice idea. I will try to implement it!

**Comment by alpha-tango-kilo** [comment]
Thanks for the incredibly fast responses!

**Comment by NotTobi** [comment]
Okay this will be trickier to implement than I thought :/
I don't feel like investing this much time into it now - especially since I don't gain anything from it personally. I will post the sign in/sing out solution in the ReadMe though, so others can easily fix it for themselves as well!
