### ISSUE TITLE
Convert to Chrome

### ISSUE THREAD

**Issue by rakor1** [NotTobi/soundcloud-dl#13]
Hi! Is it possible to convert it to chrome, bc theres no working extensions with metadata and its a little bit annoying to open up firefox just to download a music 
Anyway thx for supporting the extension!

**Comment by rakor1** [comment]
sry didnt notice that i can do it myself

**Comment by NotTobi** [comment]
Hi, the extension should support Chrome in it's current state and can already be loaded by yourself using the Developer Tools.
I've been reluctant about publishing to Chrome, since you need to give them your Credit Card details and I don't want this extension being linked to my real identity. Be aware of this.
I thought about using a prepaid Credit Card, but acquiring one is difficult due to my geographic location ^^

If you are not concerned about this stuff and would like to help me publish this extension to the Chrome Marketplace, I would be more than happy to collaborate with you! :)
