### ISSUE TITLE
Addon doesn't start download and is stuck on "Preparing"

### ISSUE THREAD

**Issue by froks** [NotTobi/soundcloud-dl#15]
When trying to download https://soundcloud.com/alesia-arkusha/sets/mind-games-podcast, I get the following error messages:

[console-export-2021-4-2_12-22-38.txt](https://github.com/NotTobi/soundcloud-dl/files/6249050/console-export-2021-4-2_12-22-38.txt)

Not using an account/not signed into soundcloud. Version is 1.9.5 (1.4.2021)

**Comment by NotTobi** [comment]
Hi, thanks for your report. I checked it out and determined it is a bug comprised of two separate issues:
1. Even though an error is correctly reported it is not delegated to the UI - Already fixed this just now.
2. Once the number of tracks exceed ~50 the SoundCloud API Endpoint I'm using to request details about the tracks throws an error - I'm actively working on a solution by splitting the tracks in a playlist, etc. into chunks as to not hit this limit of SoundCloud.

You can expect a new version where this should be fixed in half an hour or so. I will notify you here as well! :)

**Comment by NotTobi** [comment]
I just published version 1.9.6, it is not live yet, since it is still undergoing review, but should be any minute now.
With this update I am no longer able to reproduce the issue. 
Please let me know, if it solves the issue for you as well!

Happy Easter Holidays :)

**Comment by froks** [comment]
Awesome, works great. Probably also the fastest ever between reporting an issue and receiving the fix
