### ISSUE TITLE
Downloaded .m4a files show 0kbps in Windows File Explorer.

### ISSUE THREAD

**Issue by whatsupimr** [NotTobi/soundcloud-dl#4]
Hey NotTobi, I created another issue about the incorrect metadata tagging maybe a month ago, but I wanted to wait awhile before requesting another fix haha. I have noticed another issue when downloading the 256k .m4a files. In Windows File Explorer, the downloaded files show "0kbps". I can open them in Groove Music, WMP, VLC, etc.. But when I open them in iTunes, they will not even play. This issue can be fixed if I just reconvert them to 256k .m4a's, but that leads to a loss of audio quality. Is there any way to properly set the bitrate for the m4a files downloaded with this plugin? Thanks again :)

Here's a video demonstrating what I'm talking about:
https://streamable.com/cpo84r

**Comment by NotTobi** [comment]
First of all, don't worry about making too much issues. Post anything that bothers you, maybe the issues are linked, like in this case and then I can fix them in one go.
Also I'm currently not able to actively work on this project. I have finals coming up that are important for my career, so that's where my current focus lies. I've put up an disclaimer in the README file a while ago that I won't be able to work on this project up until August and by the looks of it this won't change. You can keep making issues, but don't expect a fix (from me) until August. After that I'm glad to fix any issues that arose in the time I was "gone". I hope this is not too much of a bummer and you can manage throughout the next month without this fix. Maybe there's another Downloader you can use in the meantime! :)

**Comment by NotTobi** [comment]
I'm closing this issue as I can't find the time to look into it and it seems like a minor 'non-destructive' issue. Sorry for the inconvenience! :(
