### ISSUE TITLE
File names produce subfolders

### ISSUE THREAD

**Issue by gabhab** [NotTobi/soundcloud-dl#9]
This might well be covered by the known issue of "The normalization of some track names can fail and produce wrong results", but just in case: in OS X the renaming sometimes produces subfolders, e.g. this track

[https://soundcloud.com/pender-street-steppers/nts-radio-episode-12-with-guest-noise-in-my-head2719](url)

downloads as 

folder name: Pender Street Steppers - NTS Radio Episode 12 with guest Noise In My Head (27
track name: 19).m4a

**Comment by NotTobi** [comment]
This should also be fixed with version 1.7.2. It was interpreting the `2/7/19` as path separators, which caused the confusion.
With the newest version it produces this file name: `Pender Street Steppers - NTS Radio Episode 12 with guest Noise In My Head (2719).m4a`
Let me know if this is fixed for you and whether I can close the issue or not! :)

**Comment by gabhab** [comment]
This is fixed for me, thanks again for doing this - as far as I'm concerned both issues can be closed.
